# Generated by Django 5.2.3 on 2026-05-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(blank=True, help_text='Chemical formula, e.g. C8H9NO2', max_length=50)),
                ('pka', models.FloatField(blank=True, help_text='Acid dissociation constant', null=True)),
                ('log_p', models.FloatField(help_text='Octanol-water partition coefficient')),
                ('log_kw', models.FloatField(help_text='Log of retention factor in pure water (LSS model parameter)')),
                ('s_parameter', models.FloatField(default=4.0, help_text='LSS model S parameter (slope of log k vs organic fraction)')),
                ('molecular_weight', models.FloatField(help_text='Molecular weight in g/mol')),
                ('uv_absorption_max', models.FloatField(blank=True, help_text='Wavelength of maximum UV absorption in nm', null=True)),
                ('neutral_charge', models.BooleanField(default=True, help_text='Whether analyte is neutral at typical HPLC pH')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('available_columns', models.JSONField(default=list, help_text='List of available column chemistry codes')),
                ('max_pressure_bar', models.FloatField(default=400.0, help_text='Maximum system pressure in bar')),
                ('solvent_a', models.CharField(default='Water (0.1% Formic Acid)', help_text='Description of aqueous mobile phase', max_length=100)),
                ('solvent_b', models.CharField(default='Acetonitrile', help_text='Description of organic mobile phase', max_length=100)),
                ('base_points', models.FloatField(default=10000.0, help_text='Base points for scoring calculation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analytes', models.ManyToManyField(related_name='levels', to='hplc_simulator.analyte')),
            ],
            options={
                'ordering': ['difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('best_score', models.FloatField(default=0.0)),
                ('best_resolution', models.FloatField(default=0.0)),
                ('best_run_time', models.FloatField(default=0.0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False, help_text='Whether the user has achieved baseline resolution (Rs >= 1.5)')),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='hplc_simulator.level')),
            ],
            options={
                'ordering': ['level__difficulty', 'level__name'],
                'unique_together': {('level', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('mobile_phase', models.JSONField(help_text='Mobile phase configuration')),
                ('column_config', models.JSONField(help_text='Column configuration')),
                ('operation_config', models.JSONField(help_text='Operational settings')),
                ('total_run_time', models.FloatField(help_text='Total run time in minutes')),
                ('max_pressure_bar', models.FloatField(help_text='Maximum pressure reached in bar')),
                ('min_resolution', models.FloatField(help_text='Minimum resolution between adjacent peaks')),
                ('critical_pair', models.JSONField(blank=True, help_text='Names of the two analytes forming the critical pair', null=True)),
                ('score', models.FloatField(help_text='Calculated score for this run')),
                ('is_successful', models.BooleanField(default=False, help_text='Whether Rs >= 1.5 for all adjacent pairs')),
                ('overpressure', models.BooleanField(default=False, help_text='Whether the run exceeded max pressure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='hplc_simulator.level')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['level', 'session_key'], name='hplc_simula_level_i_a61066_idx')],
            },
        ),
    ]
