# Generated by Django 5.2.3 on 2026-05-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hplc_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyte',
            name='log_kw',
            field=models.FloatField(help_text='Log of retention factor in pure water (LSS model)'),
        ),
        migrations.AddConstraint(
            model_name='levelprogress',
            constraint=models.CheckConstraint(condition=models.Q(('best_score__gte', 0)), name='levelprogress_best_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='levelprogress',
            constraint=models.CheckConstraint(condition=models.Q(('best_resolution__gte', 0)), name='levelprogress_best_resolution_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='levelprogress',
            constraint=models.CheckConstraint(condition=models.Q(('best_run_time__gte', 0)), name='levelprogress_best_run_time_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('max_pressure_bar__gte', 0)), name='userscore_max_pressure_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('min_resolution__gte', 0)), name='userscore_min_resolution_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('total_run_time__gte', 0)), name='userscore_total_run_time_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='userscore_score_non_negative'),
        ),
    ]
