# Generated by Django 5.2.3 on 2026-05-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hplc_simulator', '0002_add_check_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyte',
            name='concentration_mm',
            field=models.FloatField(default=1.0, help_text='Analyte concentration in mM for peak height calculation'),
        ),
        migrations.AddField(
            model_name='analyte',
            name='extinction_coefficient',
            field=models.FloatField(blank=True, help_text='Molar extinction coefficient (L/mol/cm) at UV absorption max', null=True),
        ),
    ]
